#name: Deploy to Google Cloud Run
#
#on:
#  workflow_run:
#    workflows: ["Java CI with Maven"]
#    types:
#      - completed
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    if: ${{ github.event.workflow_run.conclusion == 'success' }}
#
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: target  # Asegúrate de que coincide con el nombre del artefacto subido
#          path: ./target  # Carpeta destino para la descarga
#
#      - name: List target directory after download
#        run: ls -la ./target  # Verifica que el artefacto esté presente
#
#      - name: Configure Google Cloud CLI
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true
#
#      - name: Build Docker image
#        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/exchange-rate:${{ github.sha }} .
#
#      - name: Push Docker image
#        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/exchange-rate:${{ github.sha }}
#
#      - name: Deploy to Cloud Run
#        run: |
#          gcloud run deploy exchange-rate \
#            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/exchange-rate:${{ github.sha }} \
#            --platform managed \
#            --region us-central1 \
#            --allow-unauthenticated